version: "3.9"
services:
  mariadb1:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
      - ./dev/mariadb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
    container_name: mariadb
#    healthcheck:
#      test: [ "CMD", "mariadb-admin", "--protocol", "tcp" ,"ping" ]
#      timeout: 3m
#      interval: 10s
#      retries: 10

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
    container_name: 'rabbitmq'

  youtube3:
    build: youtube3/build/docker/main
    container_name: youtubeApi
    ports:
      - "8080:8080"
    volumes:
      - /home/alex/Downloads/YouTube3:/files
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db

  youtube_transcoder:
    build: youtube_transcoder/build/docker/main
    container_name: youtube_transcoder
    ports:
      - "8081:8081"
    volumes:
      - /home/alex/Downloads/YouTube3:/files
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db