micronaut:
  application:
    name: youtube_transcoder
  server:
    port: 8081
    
netty:
  default:
    allocator:
      max-order: 3


# for databased
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    jdbc-url: jdbc:mariadb://mariadb:3306/citizix_db
    username: citizix_user
    password: An0thrS3crt
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          #it is necessary because we want to create table
          auto: create
        show_sql: true

rabbitmq:
  host: rabbitmq