micronaut:
  application:
    name: common
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    jdbc-url: jdbc:mysql://mariadb:3306/citizix_db
    username: citizix_user
    password: An0thrS3crt